AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

  Sample SAM Template for dorothy_personel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DorothyPersonelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 30
      Architectures:
        - arm64
      Events:
        DorothyPersonel:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /color
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./dorothy_personel
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DorothyPersonelApi:
    Description: "API Gateway endpoint URL for Prod stage for dorothy_personel function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/color/"
  DorothyPersonelFunction:
    Description: "dorothy_personel Lambda Function ARN"
    Value: !GetAtt DorothyPersonelFunction.Arn
  DorothyPersonelFunctionIamRole:
    Description: "Implicit IAM Role created for dorothy_personel function"
    Value: !GetAtt DorothyPersonelFunctionRole.Arn
