AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

  Sample SAM Template for dorothy_SERVER

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90

Resources:
  # Dorothy API 명세
  DorothyAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
  # Dorothy API 사용량 명세
  DorothyAPIPlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn:
      - DorothyAPI
    Properties:
      ApiStages:
        - ApiId: !Ref DorothyAPI
          Stage: Prod
      Description: Setting Usage for DorothyAPI Key.
      Quota:
        Limit: 10000
        Period: MONTH
      Throttle:
        BurstLimit: 5
        RateLimit: 5
      UsagePlanName: "Dorothy-usage-plan"
  # Dorothy API Api key
  DorothyApiAccessKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn:
      - DorothyAPI
    Properties:
      Name: "Dorothy-api-key"
      Description: To use usage plan and api key in REST API.
      Tags: 
      - Key: Mode
        Value: Learning
      Enabled: true
      StageKeys:
        - RestApiId: !Ref DorothyAPI
          StageName: Prod
  # Link API key to Usage
  LinkUsagePlanApiKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId: !Ref DorothyApiAccessKey
      KeyType: API_KEY
      UsagePlanId: !Ref DorothyAPIPlan
  
  DorothyPersonelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 512
      Architectures:
        - arm64
      Events:
        DorothyPersonel:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /color
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./dorothy_personel
      DockerTag: python3.11-v1
  DorothyAgeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 1024
      Architectures:
        - arm64
      Events:
        DorothyAge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /age
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./dorothy_age
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DorothyPersonelApi:
    Description: "API Gateway endpoint URL for Prod stage for dorothy_personel function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/color/"
  DorothyAgeApi:
    Description: "API Gateway endpoint URL for Prod stage for dorothy_age function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/age/"
  DorothyPersonelFunction:
    Description: "dorothy_personel Lambda Function ARN"
    Value: !GetAtt DorothyPersonelFunction.Arn
  DorothyAgeFunction:
    Description: "dorothy_age Lambda Function ARN"
    Value: !GetAtt DorothyAgeFunction.Arn
  DorothyPersonelFunctionIamRole:
    Description: "Implicit IAM Role created for dorothy_personel function"
    Value: !GetAtt DorothyPersonelFunctionRole.Arn
